### ISSUE TITLE
Why doesn't this work on my Nintendo DS?

### ISSUE THREAD

**Issue by kapoor1992** [BryceWayne/MemoryStore#7]
Hello maintainers,

I was trying to get this setup on my Nintendo DS because the `README.md` file doesn't mention that it _isn't_ supported (maybe less time should be spent on finding the perfect emoji than actual documentation). Could you please add support for this small request?

Sincerely,
Dhruv

**Comment by naaadz** [comment]
there was a workaround discussed in the Rektor discord right after you savagely left the server last year. requests to [re-join ](https://discord.gg/ZBj9nQ7b)will be carefully considered

**Comment by BryceWayne** [comment]
Thanks for your thoughtful input! We currently have the Nintendo DS port on the roadmap, but are currently backlogged with higher priority issues. We will circle back on this as soon as we secure funding.
